FROM debian:bullseye-slim
RUN apt-get update -y
RUN apt-get install -y nano bash pip 
RUN pip install wheel gunicorn flask
WORKDIR /app
COPY ./app/ /app/
COPY ./requirements.txt /var/www/requirements.txt
#RUN pip install uWSGI
RUN pip install -r /var/www/requirements.txt
CMD ["gunicorn"  , "-b", "0.0.0.0:5000", "wsgi:app"]